# FROM litespeedtech/openlitespeed:latest
FROM hub.hamdocker.ir/litespeedtech/openlitespeed:1.8.1-lsphp83
RUN apt-get update
RUN apt-get install lsphp83-apcu lsphp83-common lsphp83-curl lsphp83-dbg lsphp83-dev lsphp83-igbinary lsphp83-imagick lsphp83-imap lsphp83-intl lsphp83-ldap lsphp83-memcached lsphp83-modules-source lsphp83-msgpack lsphp83-mysql lsphp83-opcache lsphp83-pear lsphp83-pgsql lsphp83-pspell lsphp83-redis lsphp83-snmp lsphp83-sqlite3 lsphp83-sybase lsphp83-tidy -y
# lsphp83-json lsphp83
